name: deploy

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy with AWS CodeDeploy
        run: |
          aws deploy create-deployment \
          --application-name terraform-sandbox-code-deploy-app \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name terraform-sandbox-code-deploy-group \
          --description "deployment for terraform-sandbox" \
          --github-location repository=TOMOFUMI-KONDO/CodeDeployGitHubDemo,commitId="${{ github.sha }}"
